### ISSUE TITLE
3d坐标转换

### ISSUE THREAD

**Issue by xiaoshuang112** [Zengyi-Qin/MonoGRNet#10]
老师您好，我现在得到val_out文件夹下的txt后，想通过里面的数据信息把3D框画出来。我知道输出结果为一个rect,我现在知道rect.x1, rect.y1, rect.x2, rect.y2,为实际坐标，rect.height_3d, rect.width_3d, rect.length_3d, rect.x_3d, rect.y_3d, rect.z_3d,这些3D部分应该为相对坐标，现在想知道这些3d坐标该如何转换为实际坐标

**Comment by Zengyi-Qin** [comment]
这些都是实际坐标。请参照KITTI官方配置，http://www.cvlibs.net/datasets/kitti/setup.php里的红色坐标轴就是XYZ的坐标方向，Z前X右Y下。txt文件里保存的是以米为单位的XYZ坐标。
