### ISSUE TITLE
源码与论文的对应问题

### ISSUE THREAD

**Issue by shenqingzhou** [Zengyi-Qin/MonoGRNet#13]
同学您好！

您的论文中pred_depths_delta和pred_locations_delta是经过ROIAlign后得到的：

<img width="937" alt="屏幕快照 2019-06-01 16 40 00" src="https://user-images.githubusercontent.com/20157613/58746027-f4916280-848b-11e9-8da7-4f82b0e3ef8c.png">

而在源码里：

https://github.com/Zengyi-Qin/MonoGRNet/blob/da4d49c71cd0483caf5e2e65a46df9294bf23cee/decoder/fastBox.py#L411-L412

pred_depths_delta和pred_locations_delta似乎是与early feature无关的值？

**Comment by Zengyi-Qin** [comment]
您好！
这份代码中，deltas全部合并到一起预测（直接预测refine8个角点的deltas），并不单独预测depth或location的deltas。见函数_build_refine_layer。该函数的输出直接加在全局的8个角点的坐标上。

**Comment by shenqingzhou** [comment]
> 您好！
> 这份代码中，deltas全部合并到一起预测（直接预测refine8个角点的deltas），并不单独预测depth或location的deltas。见函数_build_refine_layer。该函数的输出直接加在全局的8个角点的坐标上。

我是不是可以理解为：

- 与论文相比，这份代码的losses包含depth、location、corners loss，舍去了delta_depths、delta_locations（或者说把这些loss合并成一个计算delta_global_corners的refine loss？）

- refine delta_global_corners 这一步并没有直接出现论文中（是因为这样做效果比refine delta_depths和delta_locations效果好嘛？）

- 另外训练depth分支的时候似乎也直接使用ground truth depth而不是Instance depth？

以及在回归corners的时候，使用了3*tanh()的激活函数，这样遇到尺寸较大的目标会不会出现一些问题……

顺带问一下，这一行
https://github.com/Zengyi-Qin/MonoGRNet/blob/da4d49c71cd0483caf5e2e65a46df9294bf23cee/decoder/fastBox.py#L499
后面的location和corner都用了early feature，这里'depth_deep_feat' 是不是应该改成 'depth_early_feat'？:>

**Comment by Zengyi-Qin** [comment]
- 对
- MonoGRNet的重点其实不在refine这个操作。比之前的同类研究有显著提升的本质原因，在于论文中对于3D检测的分解（4个branches）。这个分解使得基于单目图片的3D检测能够很高效地完成。至于每个branch里面的具体细节，譬如refine什么的，不是重点。虽然refine可以带来1~3个点的AP提升，但不本质
- ground truth depth指的是GT 3D box的中心的depth，也就是instance depth。instance depth与广泛研究的pixel depth的不同在于，我们关注物体3D中心的深度，而非每个可见的像素点的深度
- 同2，这有些偏离文章的核心。其实用哪个feat差别不大，都会有1~3个点的提升

**Comment by shenqingzhou** [comment]
👌thanks！
