### ISSUE TITLE
训练执行到Running Evaluation Script时内存不断上升

### ISSUE THREAD

**Issue by Xiaohuangya317** [Zengyi-Qin/MonoGRNet#14]
您好，我执行训练到Running Evaluation Script时内存上升，完成一次Evaluation后内存不变，到下一次Evaluation时，内存继续上升直到溢出。

**Comment by Zengyi-Qin** [comment]
这个我还真没有遇到过。在Tesla P40卡（22G）用默认的config始终占用16G显存

**Comment by clearIove7777** [comment]
你好，我也遇到了这个问题，显存占用的是固定的，evaluation内存使用不断增加，导致溢出报错

**Comment by Zengyi-Qin** [comment]
抱歉我刚刚看成了显存溢出。内存溢出的话也有人遇到了这个问题，请参考这个回答
https://github.com/Zengyi-Qin/MonoGRNet/issues/12#issuecomment-498506903

> Other people also encountered memory problems in evaluation.
> Please run `make` in `./submodules/kittiEvaluation` to recompile the KITTI evaluation script.
> 
> During evaluation, the python script calls `./submodules/kittiEvaluation/evaluate_object` as a subprocess. Check `./evals/kitti_eval.py` for details.
> 
> So another solution may be killing the previous subprocess, cuz every time the evaluation script `./evals/kitti_eval.py` will call a new subprocess. But anyway I didn't encounter this problem, and I don't need to kill those processes mannually. So pls try to recompile the script as described above.

**Comment by clearIove7777** [comment]
谢谢👌

**Comment by wzan0001** [comment]
> 谢谢

请问你解决了吗？我重新编译后还会报错，16G内存

**Comment by clearIove7777** [comment]
> > 谢谢
> 
> 请问你解决了吗？我重新编译后还会报错，16G内存
我暂时也没有解决这个问题，还是会出现溢出情况

**Comment by Xiaohuangya317** [comment]
32GB内存电脑上运行 `kitti_eval.py`  `def get_results(hypes, sess, image_pl, decoded_logits, validation=True)` 中`for i, file in enumerate(files)` 时，若设置在完整train.txt/val.txt 上运行evaluation，第一次evaluation中 usd mem不断增长，cache mem 在增长后释放且较低，完成evaluation后 usd mem不会降低，直至下次evaluation继续增长溢出。
修改`for i, file in enumerate(files[:1500])`只在部分上evaluation，usd mem 与 cache mem会保持平衡，多轮evaluation也不会继续增长。
测试KittiBox时，即使在全部train.txt/val.txt 上运行evaluate，由于相对占用内存小，usd mem 与 cache mem也会保持平衡，不会多次evaluation后usd mem溢出。
