### ISSUE TITLE
something wrong with the pretrained model

### ISSUE THREAD

**Issue by cs-heibao** [Zengyi-Qin/MonoGRNet#2]
When load the pretrained model 'model_2D.pkl',  exists the following error:
    self.data_dict = pickle.load(file, encoding='latin1')
    _pickle.UnpicklingError: the STRING opcode argument must be quoted

**Comment by Zengyi-Qin** [comment]
This error is due to a wrong version of python or pickle. The script runs on Python2.7. I suggest you to set up a clear virtual environment with python2.7 and TF 1.40. No special config is needed to run the code.
