### ISSUE TITLE
Data augumentation

### ISSUE THREAD

**Issue by kl456123** [Zengyi-Qin/MonoGRNet#21]
if to resize(or flip) image, the calibration matrix will change. I know that you changed the gt_boxes_3d. So I just want to know that if I change the calib, will it work ?

BTW due to all image in kitti have the almost the same shape, so you can make it. But what if not ?

**Comment by kl456123** [comment]
I think it is very important for all monocular problems. I guess that I should keep the same calib for all transform to images and the model trained contains info of the calib.

**Comment by Zengyi-Qin** [comment]
I'm not sure whether it will work if we change the calibration. Better stays unchanged.
Basically we changed the 2D projection of the 3D boxes by flipping, via changing the gt_boxes_3d (see the _flip() in input.py, which can be a little tricky). So fundamentally we are changing a 2D point, which will also work if the images are not in the same shape.

**Comment by kl456123** [comment]
I mean if images has the different shape, you need to resize them first so that the calib will changes.

**Comment by kl456123** [comment]
Thank you first anyway. I think your data augumentation will help me. and I also use the disentangle loss(Disentangling Monocular 3D Object Detection), if it works I will release code to you. (using pytorch)

**Comment by kl456123** [comment]
Sorry I cannot predict well just from roi features=-=
BTW finally I just use geometry method to achieve the 11.03ap@0.7
![Screenshot from 2019-07-26 12-13-39](https://user-images.githubusercontent.com/10957718/61926061-9cfe0780-afa1-11e9-82b1-df6fecc4233d.png)
