### ISSUE TITLE
How to rudce GPU memory

### ISSUE THREAD

**Issue by fw509** [Zengyi-Qin/MonoGRNet#22]
Is there a way to reduce the GPU memory during training? My GPU only has 10G memory. 
How can I reduce the resolution of the image input or the batch size? 

Is it possible to provide an inference demo script?

Thanks.

**Comment by Zengyi-Qin** [comment]
Sure. Thank you for your interest. In `hypes/kittibox.json` there is a "batch_size". You can safely set it to 1 or 2 or 3.
