### ISSUE TITLE
Confusion on setting rnn_len and max_len to be 1

### ISSUE THREAD

**Issue by zhby99** [Zengyi-Qin/MonoGRNet#23]
I noticed that in `create_queues` in `kitti_input.py`, `rnn_len` is set to 1, which will finally be passed to `annotation_to_h5` as `max_len`. However, by your comment on the `annotation_to_h5` method,   max_len should be greater than the number of groundtruth boxes in most cases, so I am quite confused on the settings of `rnn_len` and `max_len`, and if it is 1, does it mean that we can only train on 1 bbox on every image even there are n gt boxes?

btw, why is it called `rnn_len`?

Please correct me if anything wrong, Thanks!

**Comment by Zengyi-Qin** [comment]
Thanks for your interest. The `rnn_len` and `max_len` are of no use in this codebase. You can safely ignore them, and they will have no effect on the pipeline since the dimension size is always 1

**Comment by zhby99** [comment]
many thanks to your explanation~
