### ISSUE TITLE
预测3D框可视化

### ISSUE THREAD

**Issue by Rosywind** [Zengyi-Qin/MonoGRNet#26]
你好，我看eval输出的结果图上只有2D框、而你论文里的demo图是有3D框结果的，请问是否有可视化脚本？

**Comment by Zengyi-Qin** [comment]
I just uploaded the visualization script

**Comment by Rosywind** [comment]
看到了，谢谢！另外，我看论文里写的是预测的the location of 3D center，实际上代码最后输出的是3D box的下表面中心点，请问训练使用的label和网络的输出就是下表面中心点吗？
