### ISSUE TITLE
Some questions about estimating the depth of instance

### ISSUE THREAD

**Issue by ShaofengZou** [Zengyi-Qin/MonoGRNet#27]
I am curious and confused about the depth estimated in your paper. Here are my questions.
1. During training, is the ground truth of instance depth used to train the model? And if used, how to obtain the ground truth of depth?
2. Can you provide a demo to estimate the depth of instance? That's would be great.
Look forward to your reply. ^ ^

**Comment by Zengyi-Qin** [comment]
Thank you for your interest.

The instance level depth refers to the 3D central depth of an object's 3D bounding box, which is labeled in the KITTI dataset. Figure 3 in our paper gives a demo of
 the instance level depth
