### ISSUE TITLE
question about instance depth map

### ISSUE THREAD

**Issue by ZhiChengHu97** [Zengyi-Qin/MonoGRNet#28]
Hi,
I have a puzzle about this paper,How did you get the instance depth map?Does it show up in your code?

Look forward to your reply.

**Comment by Zengyi-Qin** [comment]
The instance depth is the 3D central depth (the z coordinates in KITTI's setting) of the ground truth 3D box. The depth value is assigned to the nearby grids on image to obtain an instance depth map. Empty grids are masked out in training
