### ISSUE TITLE
prediction of coordinates  of 3d bbox corners is not smooth

### ISSUE THREAD

**Issue by kl456123** [Zengyi-Qin/MonoGRNet#3]
From the video you provide, I find that It is not smooth . So I want to know if the coordinates of 8 bbox corners in 3d space can be regressed well.

Thanks

**Comment by Zengyi-Qin** [comment]
See our CVPR project https://github.com/Zengyi-Qin/TLNet
The video presented is much smoother than MonoGRNet
3D anchors are used here and the network only needs to regress the offsets, which we believe contributes to the stability of anchor sizes. 3D anchors can also be applied in MonoGRNet. We don't have much time and efforts to finish this new implementation.

**Comment by kl456123** [comment]
Ok, I see. It's a good idea!
BTW if you want to predict from stereo images, may be "pseudo lidar" is the better way although it is little heavily. My friend can achieve above 40 ap@0.7 in kitti val set by using this method.

**Comment by Zengyi-Qin** [comment]
WOW that's a wonderful result !
Could you please help me ask your friend what model/method to use in order to obtain a good disparity map on KITTI? There are lots of approaches but I think your friend must have used a very good one

**Comment by kl456123** [comment]
Sorry his model is used for commerce. But I think it is not too hard to get the result, modify something from PSMNet or combine avod with frustum filter. I am not familiar with disparity estimation and he just asked the guy who  reasearch on disparity .... May be  you can do the same thing

**Comment by kl456123** [comment]
Hi, how can I do inference in a new image ? I just want to test the genealization of your algorithm .
If it works, that will be perfect ! And no need of depth gt will make it more useful !
