### ISSUE TITLE
预训练权重　/　evaluation process

### ISSUE THREAD

**Issue by kevin0525** [Zengyi-Qin/MonoGRNet#30]
您好
１．请问这个预训练权重是已经完全训练好的final权重么，我使用该预训练权重进行训练total　loss 一直在一个范围内震荡　(0.035 - 0.1)
![Picture1](https://user-images.githubusercontent.com/26395975/65399555-f8a50f80-ddef-11e9-8dea-842800a1b9e5.png)

2. 另外我在训练的时候发现 running evaluation script的时候会报一些错，但训练还是可以继续下去的．
错误包括：
sh: 1: gnuplot: not found
sh: 1: gnuplot: not found
Error: /undefinedfilename in (car_detection.eps)

Last OS error: No such file or directory
GPL Ghostscript 9.26: Unrecoverable error, exit code 1
sh: 1: pdfcrop: not found

Last OS error: No such file or directory
GPL Ghostscript 9.26: Unrecoverable error, exit code 1
sh: 1: pdfcrop: not found
等等　详见下图．
![Picture2](https://user-images.githubusercontent.com/26395975/65399632-65200e80-ddf0-11e9-899e-5b8156b74018.png)

多谢．

**Comment by Zengyi-Qin** [comment]
Hi, 权重是final的，在运行后第一次evaluate就可以达到论文中的结果。你的loss虽有震荡，但范围较小，不影响。这些报错不影响运行，它所寻找的package并不是必须的，因此可以正常运行

**Comment by kevin0525** [comment]
多谢
