### ISSUE TITLE
How to change the input image size

### ISSUE THREAD

**Issue by study-ni** [Zengyi-Qin/MonoGRNet#39]
Hi,
Thanks for the code.The input image size in your code is 1248 * 384, but I want to change the input image size to 832 * 256. However, the following error occurs when running：

ValueError: Cannot reshape a tensor with 239616 elements to shape [208,512] (106496 elements) for 'Validation/Validation/decoder/inner_layer/Reshape' (op: 'Reshape') with input shapes: [1,12,39,512], [2] and with input tensors computed as partial shapes: input[1] = [208,512].

How do I modify the input size? Thank you for your reply.

**Comment by Zengyi-Qin** [comment]
Hi,
Although it's possible to change the image size, it would take a lot of time cuz you would also need to change many configurations in the pipeline. I would suggest to use the original image size

**Comment by smahajan07** [comment]
But what if we wish to train from scratch on a new data set? We will need to change the input size. Could you point out the changes required to do so?
