### ISSUE TITLE
3D localization performance evaluate

### ISSUE THREAD

**Issue by GFENGG** [Zengyi-Qin/MonoGRNet#47]
Hello, thanks for your paper. Have you provided the relevant code to evaluate the 3D localization performance ?(that is, the mean error between the central location of predicted 3D bounding boxes and their nearest ground truths mentioned in the paper)

**Comment by Zengyi-Qin** [comment]
Thanks for your interest! The repo only contains the official KITTI evaluation code for Average Precision evaluation

**Comment by z393** [comment]
> Hello, thanks for your paper. Have you provided the relevant code to evaluate the 3D localization performance ?(that is, the mean error between the central location of predicted 3D bounding boxes and their nearest ground truths mentioned in the paper)
Have you solved this problem? I have the same question with you
