### ISSUE TITLE
About supplemental material?

### ISSUE THREAD

**Issue by Stephen-ThreeD** [Zengyi-Qin/MonoGRNet#6]
A great job that offer me so many things to learn. 
And, I noticed that there is a supplemental material about detail settings in you paper, but I can't find it by google scholar, can you tell me where can I get it ？

**Comment by Zengyi-Qin** [comment]
Could you please send me a email (qinzy16@mails.tsinghua.edu.cn)? I'll reply with the file attached. The supplemental material is a little out-of-date so we didn't put it on the web, but at least the network's structure is presented.

**Comment by Stephen-ThreeD** [comment]
Ok～thank you very much！
