### ISSUE TITLE
训练中间出错

### ISSUE THREAD

**Issue by xiaoshuang112** [Zengyi-Qin/MonoGRNet#7]
老师你好，我现在已经训练起来了，之前的问题是batchsize太大了，但现在训练中又遇到新的问题，如下：
2019-04-25 17:31:07,297 WARNING Failed to run run kitti evaluation code.
2019-04-25 17:31:07,346 WARNING Please run: `cd submodules/KittiObjective2/ && make`

我大致知道是submodules这个文件夹的问题，evaluate_object2这个我都编译成功了，现在想请教您一下这个文件夹中还需要放置哪些文件？

**Comment by Zengyi-Qin** [comment]
这个应该是KITTI官方给的evaluation code编译。可以去submodules/kittiEvaluation里直接执行make，重新编译一遍。但是其实repo里面是编译好的，不需要重新编译

**Comment by Zengyi-Qin** [comment]
另外如果重新编译了一遍，需要把编译出来的文件名修改为evaluate_object，否则找不到该文件。我刚刚更新了修正这个bug，新的repo下直接重新make是可行的。请查看submodules/kittiEvaluation/Makefile文件和你之前clone下来的那个的差别

**Comment by xiaoshuang112** [comment]
好的，谢谢老师，我在试试看
